version: "2"

services:
  config:
    image: hyness/spring-cloud-config-server
    ports:
      - "8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
    volumes:
      - ./config-repo:/config

  frontend:
    image: frontend
    ports:
      - "9081:8081"
    environment:
      CONFIG_HOST: config

  backend:
    image: backend
    ports:
      - "9080:8080"
    environment:
      CONFIG_HOST: config

#
# Oracle Database
#
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - 1521:1521
      - 5500:5500

#
# MySQL Database
#
#  mysql:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./db_data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: demo
#      MYSQL_USER: demo
#      MYSQL_PASSWORD: demo