version: "3.8"

#
# Start all services 
#

services:
  config:
    image: ${REPO}/frd-config
    ports:
      - "8888:8888"
    volumes:
      - ../config-repo:/config

  frontend:
    image: ${REPO}/frd-frontend
    depends_on:
      - config
    ports:
      - "9081:8081"
    environment:
      - CONFIG_HOST=config

  backend:
    image: ${REPO}/frd-backend
    depends_on:
      - config
      - oracle
    ports:
      - "9080:8080"
    environment:
      - CONFIG_HOST=config

#
# Oracle Database
#
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
      - "5500:5500"
