version: "3.8"

#
# Start all services with load balancer in between for scaling option
#

services:
  config:
    image: ${REPO}/frd-config
    ports:
      - "8888:8888"
    volumes:
      - ../config-repo:/config

  nginx-frontend:
    image: nginx:latest
    volumes:
      - ./nginx-fe.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "9081:4000"

  frontend:
    image: ${REPO}/frd-frontend
    depends_on:
      - config
    ports:
      - "8081"
    environment:
      CONFIG_HOST: config

  nginx-backend:
    image: nginx:latest
    volumes:
      - ./nginx-be.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "9080:4000"

  backend:
    image: ${REPO}/frd-backend
    depends_on:
      - config
      - oracle
    ports:
      - "8080"
    environment:
      CONFIG_HOST: config

#
# Oracle Database
#
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
      - "5500:5500"
