# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    services:
      oracle:
        image: oracleinanutshell/oracle-xe-11g
        ports:
          - "1521:1521"
          - "5500:5500"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
           ./scripts/InstallChrome.sh

      - name: Build with Maven
        run: mvn -B package -P docker -Dspring.profiles.active=db-service -Ddocker.repo=$REPO -Doracle.jdbc.timezoneAsRegion=false

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker image Config
        run: docker push $REPO/frd-config:latest
      - name: Publish Docker image Backend
        run: docker push $REPO/frd-backend:latest
      - name: Publish Docker image Frontend
        run: docker push $REPO/frd-frontend:latest